### ISSUE TITLE
The density of fig1E

### ISSUE THREAD

**Issue by houruiyan** [WangJL2021/scPolyA-seq#4]
Hi Junliang,

Thank you very much for your detailed code. For the figure 1E, I do not know how to get the distribution of reads in the whole gene body. Which software do you use? Could you tell me? Thank you very much! In addition, I am also interested in your thsi paper. Can I contact you by your email or other methods? Could you tell me the address of your email? Thank you very much!

Best regards,
Ruiyan

**Comment by WangJL2021** [comment]
Hi, I'm glad that you are interested in this field. 

To draw Fig1E, I used `geneBody_coverage.py` from [RSeQC](https://rseqc.sourceforge.net/) to get coverage of all genes ranging from 0 to 100% from each cell's bam file, then normalised area under curve to 1 and ploted the mean and SD of each cell from 0 to 100% with R base. The latter R code part can be found at `step3/a03_coverage_c1_10x_Smart-seq2.R` of this repo.

My email is jimmymall at 163 dot com, you can contact me here or from email as you like.

**Comment by houruiyan** [comment]
Thank you Junliang!
